install.packages("ggplot2")
library("ggplot2")
#gg stands for grammar of graphics

#creating a blank graph
p1 <- ggplot(data=mtcars, aes(x=mpg, y=wt))
#above line will show a blank graph 
p1
#line 6 created two layers the data layer and aesthetic layer
#below line no 12 is used to plot the graph using points
#for line graph replace point with line
p1 + geom_point()
p1 + geom_line()


p2 <- ggplot(data=mtcars,aes(x=mpg, y=wt,colour= gear))
p2+ geom_point()
p2+ geom_line()

p3 <- ggplot(data=mtcars,aes(x=mpg,y=wt,color=cyl,size=hp)) 
p3 + geom_point()
p3+geom_line()


or

p3 <- ggplot(data=mtcars,aes(x=mpg,y=wt,color=cyl,size=hp))+geom_point() 
p3


p2+ geom_point()+ facet_grid(cyl~.)#for horizontal
p2+ geom_point()+ facet_grid(.~cyl) #for vertical
#new program

library(nlme)
Milk
g1 <-  ggplot(data= Milk,aes(x=Time,y=protein))
g1+ geom_point()

g2 <-  ggplot(data= Milk,aes(x=Time,y=protein,color=Diet))
g2+geom_point()

g2+ geom_point(color="green")



#movie rating
movies <- read.csv("Movie Ratings.csv")

colnames(movies)
#renaming the columns for convenience
colnames(movies) <- c("Name","Genre","CriticRatings","AudienceRatings","BudgetMillions","ReleaseYear")
#check
head(movies)
str(movies)

#making releaseyear as factor(its better to always change years(time)in factors)
movies$ReleaseYear<-factor(movies$ReleaseYear)
str(movies)
summary(movies)


#graphs using ggplot
library(ggplot2)

ggplot(data=movies,aes(x=CriticRatings , y=AudienceRatings))

#adding geometry
ggplot(data=movies,aes(x=CriticRatings , y=AudienceRatings))+geom_point()

#add color
ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre))+geom_point()

#as all dots are of same size, so changing shape

ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre, size=Genre))+geom_point()

ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre, size=BudgetMillions))+geom_point()


#using facets
ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre, size=Genre))+geom_point()+facet_grid(.~Genre)
ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre, size=Genre))+geom_point()+facet_grid(Genre~.)

#in place of geom_point() can use geom_line()



#plotting with layers
p <-ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre, size=BudgetMillions))

p+geom_point() #adding geometry layer
p+geom_line() #not make sense

p+geom_point()+geom_line()   #multiple layers but not properly visible
p+geom_line()+geom_point()    #first line graph is printed first,hence point graph is over line graph


#mapping vs setting
r <- ggplot(data=movies , aes(x=CriticRatings,y=AudienceRatings))
r + geom_point(color="red")


# add color by mapping

r + geom_point(aes(colour= Genre))

#add colors by setting
r + geom_point(colour= "Blue")
r + geom_point(colour= "Yellow")
r + geom_point(aes(colour= "Red")
r+geom_point(colour="Green")

r+ geom_point(size=5)
r+ geom_point(size=10)
r+geom_point(aes(size=10))  #not to be done

#add color by mapping

r+ geom_point(aes(size=BudgetMillions))
                    
                    #change size by setingBudgetMillions))


#kin=e nd cihild 
#change size by settings
r+geom_point(aes(size=10))
r+ geom(size=4)
  
  
  #overriding asthetics
  #example 1
  p+geom_point(aes(size=Genre))
   
#example 2
p+geom_point(aes(colour=BudgetMillions))
p+geom_point()  #no permanent change in p

#example 3
p+geom_point(aes(x= BudgetMillions))




#histogram and its density charts

h<- ggplot(data=movies,aes(x=BudgetMillions))
h+ geom_histogram() 
#count is no. of movies by default x bar is divided into 30
h+ geom_histogram(bindwidth=5)
#here it will be divided into 60 coz range is from 0 to 300


#histograms and density charts
h<- ggplot(data=movies,aes(x=BudgetMillions))
h+ geom_histogram(binwidth=10) #count in graph is a statistics generated by r
#for categorical use barplot
#for continuos larger range of values use histogram
         

#adding color
h+ geom_histogram(binwidth = 10,fill="Red")#for setting red
h+ geom_histogram(binwidth = 10,fill="Red",color="Black")#making outline black
h+ geom_histogram(binwidth = 10,aes(fill=Genre),color="Black")
#fill for filling the interior and color for otlines
h+ density

#boxplots

j<- ggplot(data=movies , aes(x=Genre,y=AudienceRatings,color=Genre))
j+geom_boxplot()
j+geom_point()

j+geom_boxplot(size=1.2)+geom_point()

j<- ggplot(data=movies , aes(x=Genre,y=AudienceRatings,color=Genre))
j+geom_boxplot()




#ploting more efficiently using facets
k<- ggplot(data=movies,aes(x=BudgetMillions))
k+ geom_histogram(binwidth = 10,aes(fill=Genre),color="Black")


#for horizontal
k+ geom_histogram(binwidth = 10,aes(fill=Genre),color="Black")+facet_grid((Genre ~.))

#for vertical
k+ geom_histogram(binwidth = 10,aes(fill=Genre),color="Black")+facet_grid((.~Genre))

#for horizontal scale is common for every genre,so some values are not visible
k+ geom_histogram(binwidth = 10,aes(fill=Genre),color="Black")+facet_grid((Genre ~.), scale="free")


#taking scattered and adding facet layer
l <-ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre))
l+geom_point(size=3)+facet_grid(.~Genre)

l+geom_point(size=3)+facet_grid(Genre~.)

l+geom_point(size=3)+facet_grid(ReleaseYear~.)
l+geom_point(size=3)+facet_grid(.~ReleaseYear)


l+geom_point(size=3)+facet_grid(Genre~ReleaseYear)


#geom_smooth

l <-ggplot(data=movies, aes(x=CriticRatings, y=AudienceRatings, color=Genre))
l+geom_point()+geom_smooth()
l+geom_smooth()


#19.04.17
#perfecting by adding theme
library(ggthemes)

